require('config.lazy')
require('functions.check-backspace')
require('functions.floating-terminal')
require('functions.git-modified')
require('functions.coc-show-docs')
require('config.remap')
require('config.vimsettings')
