--require('plugins.vim-plug')
require('functions.check-backspace')
require('functions.floating-terminal')
require('functions.git-modified')
require('config.remap')
require('config.vimsettings')
require('config.lazy')
